language: node_js
node_js:
  - lts/*
env:
  - API_SERVER=https://easy-mock.com/mock/5c1b3895fe5907404e654045/femessage-mock
install:
  - yarn
script:
  - yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
